# Generated by Django 6.0.8 on 2026-08-04 22:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=80, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('display_count', models.PositiveIntegerField(default=0, help_text='عدد نمایشی روی کارت دسته در صفحه اصلی (اختیاری)')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_18k_per_gram', models.BigIntegerField(help_text='طلای ۱۸ عیار — تومان بر گرم')),
                ('price_24k_per_gram', models.BigIntegerField(default=0)),
                ('coin_emami', models.BigIntegerField(default=0)),
                ('coin_half', models.BigIntegerField(default=0)),
                ('coin_quarter', models.BigIntegerField(default=0)),
                ('usd_toman', models.BigIntegerField(default=0)),
                ('ounce_usd', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'نرخ طلا',
                'verbose_name_plural': 'نرخ\u200cهای طلا',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('shipped', 'ارسال\u200cشده'), ('cancelled', 'لغوشده')], default='pending', max_length=12)),
                ('gold_price', models.BigIntegerField(help_text='نرخ طلا در لحظه\u200cی ثبت سفارش')),
                ('total', models.BigIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('weight_g', models.DecimalField(decimal_places=2, help_text='وزن به گرم', max_digits=8)),
                ('karat', models.PositiveSmallIntegerField(default=18)),
                ('fee_ratio', models.DecimalField(decimal_places=2, default=0.2, help_text='اجرت — نسبت (0.22 = ۲۲٪)', max_digits=4)),
                ('stone_value', models.BigIntegerField(default=0, help_text='ارزش سنگ/نگین — تومان')),
                ('tag', models.CharField(blank=True, choices=[('', '—'), ('پرفروش', 'پرفروش'), ('جدید', 'جدید'), ('ویژه', 'ویژه')], default='', max_length=12)),
                ('description', models.TextField(blank=True)),
                ('placeholder_label', models.CharField(blank=True, help_text='برچسب تصویر جایگزین وقتی عکسی آپلود نشده', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.BigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt', models.CharField(blank=True, max_length=140)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['order'],
            },
        ),
    ]
