# Generated by Django 6.0.8 on 2026-08-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_079368_idx',
            old_name='orders_orde_status_c918eb_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_phone_6a6a6f_idx',
            old_name='orders_orde_phone_7a2b1c_idx',
        ),
    ]
