# Generated by Django 6.1.1 on 2026-09-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_order_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_kind',
            field=models.CharField(choices=[('full', 'خرید کامل'), ('deposit', 'بیعانه / رزرو')], db_index=True, default='full', help_text='full = خرید موجودی · deposit = رزرو با بیعانه برای سفارش ساخت', max_length=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_is_estimated',
            field=models.BooleanField(default=False, help_text='وزن از میانگین/میانه مدل\u200cهای مشابه دسته برآورد شده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('reserved', 'رزرو با بیعانه'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال\u200cشده'), ('delivered', 'تحویل\u200cشده'), ('cancelled', 'لغوشده'), ('refunded', 'مرجوع\u200cشده')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
