# Generated by Django 6.1.1 on 2026-09-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_made_to_order_deposit_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit_gold_g',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='معادل طلایی بیعانه پرداختی — طلب مشتری از گالری (گرم ۱۸ عیار)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_weight_g',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='وزن تقریبی کل سفارش (گرم) برای رزرو', max_digits=10, null=True),
        ),
    ]
