# Generated by Django 6.0.8 on 2026-08-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldprice',
            name='mesghal_17',
            field=models.BigIntegerField(default=0, help_text='مثقال ۱۷ (آبشده نقدی فراز) — تومان'),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='source',
            field=models.CharField(default='manual', help_text='manual | faraz | api | admin', max_length=40),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='usd_toman',
            field=models.BigIntegerField(default=0, help_text='Deprecated — always 0'),
        ),
    ]
