# Generated by Django 6.0.8 on 2026-08-05 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_mesghal_17'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('page_type', models.CharField(choices=[('page', 'صفحه'), ('blog', 'بلاگ')], default='page', max_length=10)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(help_text='متن صفحه — هر خط یک پاراگراف')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('show_in_nav', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صفحه محتوا',
                'verbose_name_plural': 'صفحات محتوا',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Anil', max_length=80)),
                ('brand_tagline', models.CharField(default='درخششی ابدی', max_length=120)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('cart_label', models.CharField(default='گلد باکس', max_length=40)),
                ('hero_badge', models.CharField(default='گالری طلا آنیل', max_length=80)),
                ('hero_title', models.CharField(default='طلا،\nآن\u200cگونه که باید بدرخشد', max_length=200)),
                ('hero_subtitle', models.TextField(default='مجموعه\u200cای زنده از زیورآلات دست\u200cساز، با قیمت\u200cگذاری لحظه\u200cای بر پایه\u200cی نرخ روز طلا.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_cta_primary', models.CharField(default='مشاهده\u200cی محصولات', max_length=80)),
                ('hero_cta_secondary', models.CharField(default='قیمت لحظه\u200cای طلا', max_length=80)),
                ('show_rates', models.BooleanField(default=True)),
                ('show_categories', models.BooleanField(default=True)),
                ('show_featured', models.BooleanField(default=True)),
                ('show_trust', models.BooleanField(default=True)),
                ('section_order', models.JSONField(blank=True, default=list)),
                ('top_banner', models.CharField(default='ارسال امن و بیمه\u200cشده به سراسر کشور · ضمانت اصالت و بازخرید · مشاوره\u200cی رایگان تخصصی', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات چیدمان',
                'verbose_name_plural': 'تنظیمات چیدمان',
            },
        ),
    ]
