# Generated by Django 6.1.1 on 2026-09-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_weight_nullable_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='made_to_order_deposit',
            field=models.BigIntegerField(default=5000000, help_text='بیعانه رزرو برای محصولات بدون وزن تأییدشده (تومان)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='made_to_order_deposit_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='درصد بیعانه از قیمت تقریبی (۰ = فقط مبلغ ثابت)', max_digits=5),
        ),
    ]
